{{- if and .Values.api.enabled .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "portfolio-platform.fullname" . }}-api
  labels:
    {{- include "portfolio-platform.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "portfolio-platform.api.selectorLabels" . | nindent 6 }}
{{- end }}
